# Generated by Django 4.0.6 on 2022-07-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
