# Generated by Django 4.0.6 on 2022-07-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifehack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('current', models.FloatField(default=0)),
            ],
        ),
    ]
