# Generated by Django 4.0.6 on 2022-07-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifehack', '0002_bins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bins',
            new_name='Bin',
        ),
    ]
